### ISSUE TITLE
Bot Overhead blind fire

### ISSUE THREAD

**Issue by LumberingTroll** [Solarint/SAIN#75]
Every time I see a bot doing over head blind fire they kill me with one shot and its always a head shot. It happens so frequently I can't see how it couldn't be a bug.

**Comment by Solarint** [comment]
It will be fixed in the next version. Already fixed in the 3.5 test build I released, sorry!

**Comment by Solarint** [comment]
Fixed in 3.5

**Comment by GeneralShrooms** [comment]
This is still occurring as of 3.2.1

**Comment by GeneralShrooms** [comment]
Is there a way to disable blind firing, as a temp fix before 3.5?
I'm very confused with the naming convention, the newest release is 3.2.1, but 3.5 is two years old? At any rate, this bug still occurs in 3.2.1
